config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/xadmin', as: 'rails_admin'
  devise_for :users
  root :to => "jobs#index"

  resources :jobs do
    collection do
      get :inform
      post :preview
      get :search
      get :final
    end

    member do
      post :publish
      get :verify
    end
  end

  resources :day_jobs do 
    collection do
      get :inform
      post :preview
      get :search
      get :final
    end

    member do
      post :publish
      get :verify
    end
  end

  resources :categories

  resources :subscriptions do
    member do
      get :verify
    end
  end

  get "/pages/:action" , :controller => "pages"

end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  description        :text
#  user_id            :integer
#  category_id        :integer          default(1)
#  location           :string(255)
#  apply_instruction  :text
#  created_on         :date
#  updated_on         :date
#  created_at         :datetime
#  updated_at         :datetime
#  company_name       :string(255)
#  url                :string(255)
#  email              :string(255)
#  lower_bound        :integer
#  higher_bound       :integer
#  token              :string(255)
#  is_published       :boolean
#  ip                 :string(30)
#  email_confirmed    :boolean          default(FALSE)
#  email_confirmed_at :datetime
#

class Job < ActiveRecord::Base


  belongs_to :user
  belongs_to :category, :counter_cache => true

  scope :published,  -> { where(:is_published => true ).where(:email_confirmed => true ) }
  scope :recent, -> { order("id DESC") }

  include Tokenable
  include OpenGraphable
  include PublishConcern
  include ActionView::Helpers::TextHelper

  validates :title, :presence => true
  validates :description, :presence => true
  validates :location, :presence => true
  validates :apply_instruction, :presence => true
  validates :url, :url => true, :allow_blank => true
  validates :email, :email => true

  validate :check_salary, fields: [:lower_bound, :higher_bound]



  def og_title
    ERB::Util.h("#{title} - #{company_name} - 最高薪水 #{higher_bound}")
  end



  def check_salary
    if lower_bound.blank?
      errors.add(:lower_bound, "最低薪水不能為空")
    end

    if higher_bound.blank?
      errors.add(:lower_bound, "最高薪水不能為空")
    end

    if lower_bound.to_i < 30000
      errors.add(:lower_bound, "最低薪不能低於 30000")
    end

    if higher_bound.to_i < 60000
      errors.add(:lower_bound, "最高薪要超過 66000")
    end

    if lower_bound.to_i > higher_bound.to_i
      errors.add(:lower_bound, "最高薪要能超過最低薪")
    end

  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :validate_search_key , :only => [:search]
  
  def index
    @categories = Category.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.published.find(params[:id])

    set_page_title @job.og_title
    set_page_description @job.og_description
  end


  # GET /jobs/new
  def new
    if params[:token].present?
      @job = Job.where(:token => params[:token]).first

      if @job.blank?
        @job = Job.new
      end

    else
      @job = Job.new
    end
  end




  def preview

    if params[:job][:token].present?
      @job = Job.find_by_token(params[:job][:token])
      if @job.update(job_params)
        render :preview
      else
        render :new
      end
    else

      @job = Job.new(job_params)
      @job.ip = request.remote_ip

      if !@job.save
        render :new
      end
    end

  end

  def edit
    @job = Job.find_by_token(params[:id])
  end

  def update
    @job = Job.find_by_token(params[:id])
    if @job.update(job_params_for_edit)
      flash[:notice] = "修改成功"
      redirect_to job_path(@job)
    else
      render :new
    end
  end


  def publish
    @job = Job.find_by_token(params[:id])

    flash[:notice] = "感謝您刊登此資訊，我們會寄一封信件到您信箱確認您刊登 email 有效，等您驗證過後，職缺會立即刊登"
    PublishJobService.new(@job).send_verfication_email!

    redirect_to root_path

  end

  def verify
    @job = Job.find_by_token(params[:id])

    if @job.verified?
      flash[:error] = "你已經驗證過了"
      redirect_to root_path
    else
      @job.verify!
      PublishJobService.new(@job).publish! 
      flash[:notice] = "驗證通過。您的職缺已順利刊登！"
      redirect_to job_path(@job)
    end
  end

  def final
    @job = Job.find_by_token(params[:token])
  end


  def search
    if @query_string.present?
      search_result = Job.ransack(@search_criteria).result(:distinct => true)
      @jobs = search_result.paginate(:page => params[:page], :per_page => 20 )
      set_page_title "搜尋 #{@query_string}"
    end
  end
  

  protected

  def validate_search_key
    @query_string = params[:q].gsub(/\\|\'|\/|\?/, "") if params[:q].present?
    @search_criteria = search_criteria(@query_string)
  end


  def search_criteria(query_string)
    { :title_or_description_or_email_or_location_cont => query_string }
  end




  # Never trust parameters from the scary internet, only allow the white list through.
  def job_params
    params.require(:job).permit(:lower_bound, :higher_bound, :title, :description, :location , :company_name, :category_id , :apply_instruction, :url, :email)
  end

  def job_params_for_edit
    params.require(:job).permit(:is_published,:lower_bound, :higher_bound, :title, :description, :location , :company_name, :category_id , :apply_instruction, :url, :email)
  end
end

app/helpers/jobs_helper.rb
module JobsHelper

  def render_job_title(job)
    link_to(job.title, job_path(job))
  end


  def render_job_description(job)
    sanitize(job.description.to_markdown)
  end

  def render_explore_job_desc(job)
    if job.og_description.present?
      content_tag(:p, job.og_description, :class => "job-desc")
    end
  end

  def render_job_apply_instruction(job)
    job.apply_instruction.to_markdown
  end

  def render_job_url(job)
    link_to(job.url, job.url)
  end

  def render_job_warning(salary)
    if salary < 35000
      "[最低薪 < 35000 請自行斟酌是否應徵此公司]"
    end
  end
  
  def render_job_salary(salary)

    special_label = if salary >= 200000
      "label-danger"
    elsif salary >= 100000
      "label-success"
    else
      ""
    end

    salary = number_to_currency(salary, precision: 0)

    content_tag(:span, "新台幣 #{salary} 元", :class => "label label-default #{special_label}")
  end

  def render_job_fresh_state(job)
    if job.created_on >= Date.today - 1.days
      content_tag(:span, "NEW", :class => "label label-success")
    end


  end

  def render_job_company_name(job)
    if job.url.present?
      link_to(job.company_human_name, job.url, :target => "_blank")
    else
      job.company_human_name
    end
  end
end

app/views/jobs/_form.html.erb
<%= simple_form_for @job , :url =>  preview_jobs_path , :method => :post,  html: { class: 'form-horizontal' } , :wrapper => :horizontal_form,  :wrapper_mappings => {    check_boxes: :horizontal_radio_and_checkboxes,    radio_buttons: :horizontal_radio_and_checkboxes,    file: :horizontal_file_input,    boolean: :horizontal_boolean } do |f| %>




       <h4 class="instruction"> &nbsp; &nbsp;&nbsp;第一步，告訴我們詳細資訊 </h4>


    <%= f.input :title, :label => "Job Title", :hint => "“Senior Designer” or “Rails Programmer”" %>

    <% @categories = Category.all.map{ |c| [c.name, c.id] } %>

    <%= f.input :category_id, :collection => @categories ,    as: :radio_buttons, :checked => @categories[1] %>


     <%= f.input :lower_bound , :label => '薪水', :wrapper => :prepend_append do  %>
         <%= f.input_field :lower_bound, :as => :string, placeholder: '下限 (Lower bound)' %> ~
         <%= f.input_field :higher_bound, :as => :string, placeholder: '上限 (Higher bound)' %>
     <% end %>


    <%= f.input :location, :label => "工作地點", :hint => "臺北 / 高雄 / 上海 / ...etc." %>

      <%= f.input :description, :label => "工作敘述", :input_html => { :rows => 10, :data => { :provide => "markdown"} }, :hint => "使用 Markdown 語法" %>

    <%= f.input :apply_instruction, :label => "如何應徵", :hint => "Example: Send a resume to hr@mycompany.com" , :input_html => { :rows => 3 } %>


    <h4 class="instruction"> &nbsp; &nbsp;&nbsp;介紹你的公司 </h4>

    <br><br>


    <%= f.input :company_name, :input_html => { :class => "col-lg-4"}, :label => "公司 / 組織名稱", :hint => "Enter your company or organization’s name."%>

    <%= f.input :url, :label => "URL" %>
    <%= f.input :email, :hint => "This is where we’ll send your receipt and confirmation email." %>

    <%= f.input :token, :as => :hidden, :valie => @job.token if !@job.new_record? %>
<hr>

<div class="form-group text optional job_description">
  <label class="text optional col-sm-1 control-label" for="job_description"></label>
  <div class="col-sm-11">
      <%= f.submit "預覽徵才啟事" , :class => "btn btn-lg btn-danger" %>
  </div>
</div>


<% end %>

app/views/jobs/_inform.html.erb
 <div class="modal-dialog">
      <div class="modal-content">


        <div class="modal-body" style="text-align:center;">


          <h3> 感謝你願意在這裡分享 66K+ 的工作 </h3>

            <%= image_tag("shakehand.png") %>
            
          <h4> 66K 工作網是一個專門讓大家張貼以及找到好工作的求職網站。 </h4>


          <br><br>

            <%= link_to("馬上來張貼好工作吧！", new_job_path, :class => "btn btn-lg btn-default btn-primary" ) %>
        <br><br>
   
            <p> <a href="#" style="color:#ccc; text-decoration:underline;" data-dismiss="modal"> 我改變心意了，我想貼的這個工作不值得 66 K </a> </p>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->

app/views/jobs/_item.html.erb
<tr>

  <td width="80%">
    <%= render_job_fresh_state(job) %>

    <%= job.company_human_name %> -
    <%= render_job_title(job) %>
    <%= render_job_warning(job.lower_bound) %>
  </td>
  <td width="5%">
    <%= render_job_salary(job.higher_bound) %>
  </td>
  <td> <%= job.created_on.to_s(:short) %> </td>
</tr>

app/views/jobs/_preview_block.html.erb
<h2> <%= @job.title %> @ <%= render_job_company_name(@job) %> </h2>

<div class="group">
  <span style="color:grey; font-weight:bold;"> <i class="glyphicon glyphicon-calendar"> </i> 刊登日期 <%= @job.created_on.to_s(:long) %> </span>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <span style="color:grey; font-weight:bold;"> <i class="glyphicon glyphicon-map-marker"></i> 上班地點 <%= @job.location %> </span>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <span style="color:grey; font-weight:bold;" class="pull-right">
   <%= render_job_warning(@job.lower_bound) %>
   <%= render_job_salary(@job.lower_bound)%>  ~ <%= render_job_salary(@job.higher_bound)%> 
   </span>
</div>



<hr>

<div class="job-desc">
  <p>
    <%= render_job_description(@job) %>
  </p>

</div>
<br>

<div class="well">
  <h4> 應徵方法 </h4>
  <p>
    <%= render_job_apply_instruction(@job) %>
  </p>

</div>

app/views/jobs/_search_bar.html.erb
<div class="row">
  <div class="col-sm-9 col-lg-8 col-lg-offset-2">
    <%= form_tag search_jobs_path , :method => :get, :class => "jobs-search-form" do %>
      <div class="input-group">
        <input type="text" class="form-control" name="q" value="<%= params[:q] %>" placeholder="搜尋工作關鍵字...">

        <span class="input-group-btn">
          <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
          </button>
        </span>
      </div>
    <% end %>
  </div>

  <div class="col-sm-3 col-lg-2">
    <%= link_to '張貼一份 66K+ 工作' , inform_jobs_path, :remote => true, :class => "btn btn-primary btn-block" %>
  </div>
</div>

app/views/jobs/edit.html.erb
<%= simple_form_for @job , :url =>  job_path(@job.token) ,  html: { class: 'form-horizontal' } , :wrapper => :horizontal_form,  :wrapper_mappings => {    check_boxes: :horizontal_radio_and_checkboxes,    radio_buttons: :horizontal_radio_and_checkboxes,    file: :horizontal_file_input,    boolean: :horizontal_boolean } do |f| %>


    <h4 class="instruction red"> &nbsp; &nbsp;&nbsp;修改工作資訊 </h4>


    <%= f.input :title, :label => "Job Title", :hint => "“Senior Designer” or “Rails Programmer”" %>

    <% @categories = Category.all.map{ |c| [c.name, c.id] } %>
  
    <%= f.input :category_id, :collection => @categories ,    as: :radio_buttons, :checked => @categories[1] %>


     <%= f.input :lower_bound , :label => '薪水', :wrapper => :prepend_append do  %>
         <%= f.input_field :lower_bound, :as => :string %>
         <%= f.input_field :higher_bound, :as => :string %>
     <% end %>


    <%= f.input :location, :label => "工作地點", :hint => "臺北 / 高雄 / 上海 / ...etc." %>

    <%= f.input :description, :label => "工作敘述", :input_html => { :rows => 10, :data => { :provide => "markdown"} }, :hint => "使用 Markdown 語法" %>

    <%= f.input :apply_instruction, :label => "如何應徵", :hint => "Example: Send a resume to hr@mycompany.com" , :input_html => { :rows => 3 } %>


    <h4 class="instruction"> &nbsp; &nbsp;&nbsp;介紹你的公司 </h4>

    <br><br>


    <%= f.input :company_name, :input_html => { :class => "col-lg-4"}, :label => "公司 / 組織名稱", :hint => "Enter your company or organization’s name."%>

    <%= f.input :url, :label => "URL" %>
    <%= f.input :email, :hint => "This is where we’ll send your receipt and confirmation email." %>
    <%= f.input :is_published, :label => "上架" %>
    <%= f.input :token, :as => :hidden, :valie => @job.token if !@job.new_record? %>
<hr>

<div class="form-group text optional job_description">
  <label class="text optional col-sm-1 control-label" for="job_description"></label>
  <div class="col-sm-11">
      <%= f.submit "儲存" , :class => "btn btn-lg btn-danger" %>
  </div>
</div>


<% end %>

app/views/jobs/final.html.erb
<div class="stepwizard">
    <div class="stepwizard-row">
        <div class="stepwizard-step">
          <%= link_to("1", new_job_path(:token => @job.token), :class => "btn btn-default btn-circle") %>
      
            <p>張貼工作內容</p>
        </div>
        <div class="stepwizard-step">
            <button type="button" class="btn btn-default btn-circle" disabled="disabled">2</button>
            <p>預覽</p>
        </div>
        <div class="stepwizard-step">
          <%= link_to("3", final_jobs_path(:token => @job.token ), :class => "btn btn-primary btn-circle") %>
            <p>確定張貼</p>
        </div> 
    </div>
</div>


<div class="new-job">

  <h3> STEP 3 : 確定張貼廣告 </h3>

  <hr>


<div class="well">

  <ul>
    <li> 你的廣告會在本站首頁上停留三十天（從現在算起）。 </li>
    <li> 一則廣告只允許公告一個職缺 </li>
    <li> 我們保留將廣告徹架的權利 </li>
    <li> 如有任何疑問，請來信 66kjobs.tw@gmail.com </li>
  </ul>

<br>

  <div style="text-align:left;">
    <%= link_to("確定刊登本廣告", publish_job_path(@job.token), :method => :post, :confirm => "Are you sure? " , :class => "btn btn-large btn-danger") %> or <%= link_to("回去做些小改動", new_job_path(:token => @job.token) , :class => "underline red" )%>

  </div>


</div>

app/views/jobs/index.html.erb
<div class="hero-block">
  <div class="hero-inner">
    <h1 class="hero-title"> 66K 工作網 </h1>

    <div class="hero-desc">
      <p class="lead">
        <%= link_to("66K 工作網", "/") %> 是一個提供 66K+ 新台幣工作機會的求職網站。
      </p>
      <p class="lead">
        我們希望藉由這個網站，能讓大家找到且應徵上高薪且優質的工作。 憑藉自己的努力和天份也會變 Winner。
      </p>
    </div>

  </div>
</div>

<%= render :partial => "jobs/search_bar" %>

<br>

<div class="bs-example bs-example-tabs">
    <ul id="myTab" class="nav nav-tabs" role="tablist">
      <% @categories.each_with_index do |category, i| %>
      <% active_flag = "active" if i == 1 %>

        <%= content_tag :li , :class => active_flag do %>
     
          <%= link_to(category.name, "#category-#{i}", :data => { :toggle => :tab } ) %>
        <% end %> 
      <% end %>
    </ul>
    <div id="myTabContent" class="tab-content">

      <% @categories.each_with_index do |category, i| %>
      <% active_flag = "active" if i == 1 %>

        <%= content_tag :div , :class => "#{active_flag} tab-pane fade in", :id => "category-#{i}" do %>
  
         
           <h3> <%= link_to(category.name, category_path(category), :style => "color: black;") %> <%= link_to(image_tag("rss-feed.png"), category_path(category, params.merge(:format => :rss) )) %> </h3>  


          <%= render_cell :category, :jobs, :category => category %>
        <% end %> 
      <% end %>
    </div>
  </div>

app/views/jobs/inform.js.erb
$("#modal-from-dom").modal({show:true, backdrop: true});
$("#modal-from-dom").html('<%= escape_javascript(render :partial => "inform") %>');

app/views/jobs/new.html.erb
<div class="stepwizard">
    <div class="stepwizard-row">
        <div class="stepwizard-step">
            <button type="button" class="btn btn-primary btn-circle">1</button>
            <p>張貼工作內容</p>
        </div>
        <div class="stepwizard-step">
            <button type="button" class="btn btn-default btn-circle" disabled="disabled">2</button>
            <p>預覽</p>
        </div>
        <div class="stepwizard-step">
            <button type="button" class="btn btn-default btn-circle" disabled="disabled">3</button>
            <p>確定張貼</p>
        </div> 
    </div>
</div>


<div class="new-job">


  <p class="new-job-desc">
    你張貼的工作會在這個網站上停留三十天，三十天過後這個徵才啟事會過期，你可以隨時再回來重新張貼工作廣告。
   </p>  

  <br><br>
  <h3> STEP 1 : 撰寫工作內容 </h3>

  <hr>



<br><br>

  <%= render 'form' %>


</div>

app/views/jobs/preview.html.erb
<div class="stepwizard">
    <div class="stepwizard-row">
        <div class="stepwizard-step">
          <%= link_to("1", new_job_path(:token => @job.token), :class => "btn btn-default btn-circle") %>
      
            <p>張貼工作內容</p>
        </div>
        <div class="stepwizard-step">
            <button type="button" class="btn btn-primary btn-circle" disabled="disabled">2</button>
            <p>預覽</p>
        </div>
        <div class="stepwizard-step">
          <%= link_to("3", final_jobs_path(:token => @job.token ), :class => "btn btn-default btn-circle") %>
            <p>確定張貼</p>
        </div> 
    </div>
</div>


<div class="new-job">
  <br><br>


  <h3> STEP 2 : 預覽你的徵才廣告 </h3>

  <div style="text-align:right;">
    <%= link_to("看起來很不錯，繼續前進到步驟 3 ", final_jobs_path(:token => @job.token ) , :class => "btn btn-large btn-danger") %> or <%= link_to("回去做些小改動", new_job_path(:token => @job.token) , :class => "underline red" )%>

  </div>
  <hr>

  <br><br>

  <%= render :partial => "preview_block" %>


  <hr>

  <div style="text-align:left;">
    <%= link_to("看起來很不錯，繼續前進到步驟 3 ", final_jobs_path(:token => @job.token ) , :class => "btn btn-large btn-danger") %> or <%= link_to("回去做些小改動", new_job_path(:token => @job.token) , :class => "underline red" )%>

  </div>

  <br>
</div>

app/views/jobs/search.html.erb
<%= render :partial => "jobs/search_bar" %>

<br>
<div class="search-result">

  <table class="table table-borderd">
   <%= render :partial => "jobs/item", :collection => @jobs, :as => :job %>
 </table>

</div>

app/views/jobs/show.html.erb
<div class="job-nav-bar">
  <%= link_to("← 回工作列表", root_path, :class => "underline") %>

    <%= link_to("看更多 #{@job.category.name} 的工作 →", category_path(@job.category) , :class => "underline pull-right") %>

</div>

<div class="job-content">


  <%= render :partial => "jobs/preview_block" %>

</div>