config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/xadmin', as: 'rails_admin'
  devise_for :users
  root :to => "jobs#index"

  resources :jobs do
    collection do
      get :inform
      post :preview
      get :search
      get :final
    end

    member do
      post :publish
      get :verify
    end
  end

  resources :day_jobs do 
    collection do
      get :inform
      post :preview
      get :search
      get :final
    end

    member do
      post :publish
      get :verify
    end
  end

  resources :categories

  resources :subscriptions do
    member do
      get :verify
    end
  end

  get "/pages/:action" , :controller => "pages"

end

app/models/day_job.rb
# == Schema Information
#
# Table name: day_jobs
#
#  id                 :integer          not null, primary key
#  title              :string(255)
#  description        :text
#  location           :string(255)
#  apply_instruction  :text
#  created_on         :date
#  updated_on         :date
#  company_name       :string(255)
#  url                :string(255)
#  email              :string(255)
#  lower_bound        :integer
#  higher_bound       :integer
#  token              :string(255)
#  is_published       :boolean          default(FALSE)
#  ip                 :string(255)
#  email_confirmed    :boolean
#  email_confirmed_at :datetime
#  created_at         :datetime
#  updated_at         :datetime
#

class DayJob < ActiveRecord::Base

  scope :published,  -> { where(:is_published => true ).where(:email_confirmed => true ) }
  scope :recent, -> { order("id DESC") }

  include Tokenable
  include OpenGraphable
  include PublishConcern
  include ActionView::Helpers::TextHelper

  validates :title, :presence => true
  validates :description, :presence => true
  validates :location, :presence => true
  validates :apply_instruction, :presence => true
  validates :url, :url => true, :allow_blank => true
  validates :email, :email => true

  validate :check_salary, fields: [:lower_bound, :higher_bound]

  def og_title
    ERB::Util.h("（日薪專區）#{title} - #{company_name} - 最高日薪 #{higher_bound}")
  end



 def check_salary
    if lower_bound.blank?
      errors.add(:lower_bound, "最低薪水不能為空")
    end

    if higher_bound.blank?
      errors.add(:lower_bound, "最高薪水不能為空")
    end

    if lower_bound.to_i < 1800
      errors.add(:lower_bound, "最低薪不能低於 1800")
    end

    if higher_bound.to_i < 2200
      errors.add(:lower_bound, "最高薪要超過 2200")
    end

    if lower_bound.to_i >= higher_bound.to_i
      errors.add(:lower_bound, "最高薪要能超過最低薪")
    end

  end

end

app/controllers/day_jobs_controller.rb
class DayJobsController < ApplicationController

  def index
    @day_jobs = DayJob.published
    set_page_title "日薪專區"
  end


  def show
    @day_job = DayJob.published.find(params[:id])

    set_page_title @day_job.og_title
    set_page_description @day_job.og_description
  end



  def edit
    @day_job = DayJob.find_by_token(params[:id])
  end

  def update
    @day_job = DayJob.find_by_token(params[:id])
    if @day_job.update(day_job_params_for_edit)
      flash[:notice] = "修改成功"
      redirect_to day_job_path(@day_job)
    else
      render :new
    end
  end

  def new
    if params[:token].present?
      @day_job = DayJob.where(:token => params[:token]).first

      if @day_job.blank?
        @day_job = DayJob.new
      end

    else
      @day_job = DayJob.new
    end
  end

  def preview


    if params[:day_job][:token].present?
      @day_job = DayJob.find_by_token(params[:day_job][:token])
      if @day_job.update(day_job_params)
        render :preview
      else
        render :new
      end
    else

      @day_job = DayJob.new(day_job_params)
      @day_job.ip = request.remote_ip

      if !@day_job.save
        render :new
      end
    end


  end


  def publish
    @day_job = DayJob.find_by_token(params[:id])

    flash[:notice] = "感謝您刊登此資訊，我們會寄一封信件到您信箱確認您刊登 email 有效，等您驗證過後，職缺會立即刊登"
    PublishDayJobService.new(@day_job).send_verfication_email!

    redirect_to root_path

  end

  def verify
    @day_job = DayJob.find_by_token(params[:id])

    if @day_job.verified?
      flash[:error] = "你已經驗證過了"
      redirect_to root_path
    else
      @day_job.verify!
      PublishDayJobService.new(@day_job).publish! 
      flash[:notice] = "驗證通過。您的職缺已順利刊登！"
      redirect_to day_job_path(@day_job)
    end
  end

  def final
    @day_job = DayJob.find_by_token(params[:token])
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def day_job_params
      params.require(:day_job).permit(:lower_bound, :higher_bound, :title, :description, :location , :company_name, :category_id , :apply_instruction, :url, :email)
   end

    def day_job_params_for_edit
    params.require(:day_job).permit(:is_published,:lower_bound, :higher_bound, :title, :description, :location , :company_name, :category_id , :apply_instruction, :url, :email)
  end
end

app/helpers/day_jobs_helper.rb
module DayJobsHelper


 def render_day_job_title(job)
    link_to(job.title, day_job_path(job))
  end

  def render_day_job_salary(salary)

    special_label = if salary >= 6500
      "label-danger"
    elsif salary >= 3500
      "label-success"
    else
      ""
    end

    salary = number_to_currency(salary, precision: 0)

    content_tag(:span, "新台幣 #{salary} 元", :class => "label label-default #{special_label}")
  end

end

app/views/day_jobs/_form.html.erb
<%= simple_form_for @day_job , :url =>  preview_day_jobs_path , :method => :post,  html: { class: 'form-horizontal' } , :wrapper => :horizontal_form,  :wrapper_mappings => {    check_boxes: :horizontal_radio_and_checkboxes,    radio_buttons: :horizontal_radio_and_checkboxes,    file: :horizontal_file_input,    boolean: :horizontal_boolean } do |f| %>




    <h4 class="instruction"> &nbsp; &nbsp;&nbsp;第一步，告訴我們詳細資訊 </h4>


    <%= f.input :title, :label => "Job Title", :hint => "“Senior Designer” or “Rails Programmer”" %>


     <%= f.input :lower_bound , :label => '薪水', :wrapper => :prepend_append do  %>
         <%= f.input_field :lower_bound, :as => :string, placeholder: '下限 (Lower bound)' %> ~
         <%= f.input_field :higher_bound, :as => :string, placeholder: '上限 (Higher bound)' %>
     <% end %>


    <%= f.input :location, :label => "工作地點", :hint => "臺北 / 高雄 / 上海 / ...etc." %>

      <%= f.input :description, :label => "工作敘述", :input_html => { :rows => 10, :data => { :provide => "markdown"} }, :hint => "使用 Markdown 語法" %>

    <%= f.input :apply_instruction, :label => "如何應徵", :hint => "Example: Send a resume to hr@mycompany.com" , :input_html => { :rows => 3 } %>


    <h4 class="instruction"> &nbsp; &nbsp;&nbsp;介紹你的公司 </h4>

    <br><br>


    <%= f.input :company_name, :input_html => { :class => "col-lg-4"}, :label => "公司 / 組織名稱", :hint => "Enter your company or organization’s name."%>

    <%= f.input :url, :label => "URL" %>
    <%= f.input :email, :hint => "This is where we’ll send your receipt and confirmation email." %>

    <%= f.input :token, :as => :hidden, :valie => @day_job.token if !@day_job.new_record? %>
<hr>

<div class="form-group text optional job_description">
  <label class="text optional col-sm-1 control-label" for="job_description"></label>
  <div class="col-sm-11">
      <%= f.submit "預覽徵才啟事" , :class => "btn btn-lg btn-danger" %>
  </div>
</div>


<% end %>

app/views/day_jobs/_item.html.erb
<tr>

  <td width="80%">
    <%= render_job_fresh_state(job) %>

    <%= job.company_human_name %> -
    <%= render_day_job_title(job) %>
  </td>
  <td width="5%">
    <%= render_day_job_salary(job.higher_bound) %>
  </td>
  <td> <%= job.created_on.to_s(:short) %> </td>
</tr>

app/views/day_jobs/_preview_block.html.erb
<h2> <%= @day_job.title %> @ <%= render_job_company_name(@day_job) %> </h2>

<div class="group">
  <span style="color:grey; font-weight:bold;"> <i class="glyphicon glyphicon-calendar"> </i> 刊登日期 <%= @day_job.created_on.to_s(:long) %> </span>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <span style="color:grey; font-weight:bold;"> <i class="glyphicon glyphicon-map-marker"></i> 上班地點 <%= @day_job.location %> </span>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <span style="color:grey; font-weight:bold;" class="pull-right">
   <%= render_day_job_salary(@day_job.lower_bound)%>  ~ <%= render_day_job_salary(@day_job.higher_bound)%> 
   </span>
</div>



<hr>

<div class="job-desc">
  <p>
    <%= render_job_description(@day_job) %>
  </p>

</div>
<br>

<div class="well">
  <h4> 應徵方法 </h4>
  <p>
    <%= render_job_apply_instruction(@day_job) %>
  </p>

</div>

app/views/day_jobs/edit.html.erb
<%= simple_form_for @day_job , :url => day_job_path(@day_job.token) ,  html: { class: 'form-horizontal' } , :wrapper => :horizontal_form,  :wrapper_mappings => {    check_boxes: :horizontal_radio_and_checkboxes,    radio_buttons: :horizontal_radio_and_checkboxes,    file: :horizontal_file_input,    boolean: :horizontal_boolean } do |f| %>


    <h4 class="instruction red"> &nbsp; &nbsp;&nbsp;修改工作資訊 </h4>


    <%= f.input :title, :label => "Job Title", :hint => "“Senior Designer” or “Rails Programmer”" %>


     <%= f.input :lower_bound , :label => '薪水', :wrapper => :prepend_append do  %>
         <%= f.input_field :lower_bound, :as => :string %>
         <%= f.input_field :higher_bound, :as => :string %>
     <% end %>


    <%= f.input :location, :label => "工作地點", :hint => "臺北 / 高雄 / 上海 / ...etc." %>

    <%= f.input :description, :label => "工作敘述", :input_html => { :rows => 10, :data => { :provide => "markdown"} }, :hint => "使用 Markdown 語法" %>

    <%= f.input :apply_instruction, :label => "如何應徵", :hint => "Example: Send a resume to hr@mycompany.com" , :input_html => { :rows => 3 } %>


    <h4 class="instruction"> &nbsp; &nbsp;&nbsp;介紹你的公司 </h4>

    <br><br>


    <%= f.input :company_name, :input_html => { :class => "col-lg-4"}, :label => "公司 / 組織名稱", :hint => "Enter your company or organization’s name."%>

    <%= f.input :url, :label => "URL" %>
    <%= f.input :email, :hint => "This is where we’ll send your receipt and confirmation email." %>
    <%= f.input :is_published, :label => "上架" %>
    <%= f.input :token, :as => :hidden, :valie => @day_job.token if !@day_job.new_record? %>
<hr>

<div class="form-group text optional job_description">
  <label class="text optional col-sm-1 control-label" for="job_description"></label>
  <div class="col-sm-11">
      <%= f.submit "儲存" , :class => "btn btn-lg btn-danger" %>
  </div>
</div>


<% end %>

app/views/day_jobs/final.html.erb
<div class="stepwizard">
    <div class="stepwizard-row">
        <div class="stepwizard-step">
          <%= link_to("1", new_day_job_path(:token => @day_job.token), :class => "btn btn-default btn-circle") %>
      
            <p>張貼工作內容</p>
        </div>
        <div class="stepwizard-step">
            <button type="button" class="btn btn-default btn-circle" disabled="disabled">2</button>
            <p>預覽</p>
        </div>
        <div class="stepwizard-step">
          <%= link_to("3", final_day_jobs_path(:token => @day_job.token ), :class => "btn btn-primary btn-circle") %>
            <p>確定張貼</p>
        </div> 
    </div>
</div>


<div class="new-job">

  <h3> STEP 3 : 確定張貼廣告 </h3>

  <hr>


<div class="well">

  <ul>
    <li> 你的日薪廣告會在本站首頁上停留十五天（從現在算起）。 </li>
    <li> 一則廣告只允許公告一個職缺 </li>
    <li> 我們保留將廣告徹架的權利 </li>
    <li> 如有任何疑問，請來信 66kjobs.tw@gmail.com </li>
  </ul>

<br>

  <div style="text-align:left;">
    <%= link_to("確定刊登本廣告", publish_day_job_path(@day_job.token), :method => :post, :confirm => "Are you sure? " , :class => "btn btn-large btn-danger") %> or <%= link_to("回去做些小改動", new_day_job_path(:token => @day_job.token) , :class => "underline red" )%>

  </div>


</div>

app/views/day_jobs/index.html.erb
<h3> 日薪專區 </h3>

    <%= link_to '張貼一份 2.2K+ 日薪工作' , new_day_job_path, :class => "btn btn-primary pull-right" %>

    <br><br>



  <table class="table table-borderd">

      <%= render :partial => "day_jobs/item", :collection => @day_jobs, :as => :job %>

  </table>

app/views/day_jobs/new.html.erb
<div class="stepwizard">
    <div class="stepwizard-row">
        <div class="stepwizard-step">
            <button type="button" class="btn btn-primary btn-circle">1</button>
            <p>張貼工作內容</p>
        </div>
        <div class="stepwizard-step">
            <button type="button" class="btn btn-default btn-circle" disabled="disabled">2</button>
            <p>預覽</p>
        </div>
        <div class="stepwizard-step">
            <button type="button" class="btn btn-default btn-circle" disabled="disabled">3</button>
            <p>確定張貼</p>
        </div> 
    </div>
</div>


<div class="new-job">


  <p class="new-job-desc">
    你張貼的日薪工作會在這個網站上停留十五天，十五天過後這個徵才啟事會過期，你可以隨時再回來重新張貼工作廣告。
   </p>  

  <br><br>
  <h3> STEP 1 : 撰寫日薪工作內容 </h3>

  <hr>



<br><br>

  <%= render 'form' %>


</div>

app/views/day_jobs/preview.html.erb
<div class="stepwizard">
    <div class="stepwizard-row">
        <div class="stepwizard-step">
          <%= link_to("1", new_day_job_path(:token => @day_job.token), :class => "btn btn-default btn-circle") %>
      
            <p>張貼工作內容</p>
        </div>
        <div class="stepwizard-step">
            <button type="button" class="btn btn-primary btn-circle" disabled="disabled">2</button>
            <p>預覽</p>
        </div>
        <div class="stepwizard-step">
          <%= link_to("3", final_day_jobs_path(:token => @day_job.token ), :class => "btn btn-default btn-circle") %>
            <p>確定張貼</p>
        </div> 
    </div>
</div>


<div class="new-job">
  <br><br>


  <h3> STEP 2 : 預覽你的徵才廣告 </h3>

  <div style="text-align:right;">
    <%= link_to("看起來很不錯，繼續前進到步驟 3 ", final_day_jobs_path(:token => @day_job.token ) , :class => "btn btn-large btn-danger") %> or <%= link_to("回去做些小改動", new_day_job_path(:token => @day_job.token) , :class => "underline red" )%>

  </div>
  <hr>

  <br><br>

  <%= render :partial => "preview_block" %>


  <hr>

  <div style="text-align:left;">
    <%= link_to("看起來很不錯，繼續前進到步驟 3 ", final_day_jobs_path(:token => @day_job.token ) , :class => "btn btn-large btn-danger") %> or <%= link_to("回去做些小改動", new_day_job_path(:token => @day_job.token) , :class => "underline red" )%>

  </div>

  <br>
</div>

app/views/day_jobs/show.html.erb
<div class="job-nav-bar">
  <%= link_to("← 回工作列表", day_jobs_path, :class => "underline") %>



</div>

<div class="job-content">


  <%= render :partial => "day_jobs/preview_block" %>

</div>