config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/xadmin', as: 'rails_admin'
  devise_for :users
  root :to => "jobs#index"

  resources :jobs do
    collection do
      get :inform
      post :preview
      get :search
      get :final
    end

    member do
      post :publish
      get :verify
    end
  end

  resources :day_jobs do 
    collection do
      get :inform
      post :preview
      get :search
      get :final
    end

    member do
      post :publish
      get :verify
    end
  end

  resources :categories

  resources :subscriptions do
    member do
      get :verify
    end
  end

  get "/pages/:action" , :controller => "pages"

end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  def new
    @subscription = EmailSubscription.new
    set_page_title "訂閱工作速遞"
  end

  def create
    @subscription = EmailSubscription.new(subscription_params)

    if @subscription.save
      SubscriptionMailer.confirm_email(@subscription).deliver
      redirect_to new_subscription_path , :notice => "感謝您對 66K 職缺有興趣，我們會寄送一封郵件給您確認 Email 位址。"
    else
      render :new
    end
  end

  def verify
    @subscription = EmailSubscription.find_by_token(params[:id])

    @subscription.subscribe_to!(Setting.newspaper_email)

    redirect_to root_path , :notice => "訂閱電子報成功"
  end


  private

  def subscription_params
    params.require(:email_subscription).permit(:email,:name)
  end

end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/new.html.erb
<div class="well landing">
  <h2> 工作快遞 </h2>

  <div class="desc">
   <p>
    <ul>
      <li>本服務免費</li>
      <li>每兩天寄送一次「本站全新工作」給您。</li>
      <li>您可以選擇隨時隨地退訂</li>
    </ul>

  </p>
</div>



</div>


<div class="group">

  <h2> 請輸入電子郵件帳號 </h2>

  <%= simple_form_for @subscription, :url => subscriptions_path ,  html: { class: 'form-horizontal' } , :wrapper => :horizontal_form,  :wrapper_mappings => {    check_boxes: :horizontal_radio_and_checkboxes,    radio_buttons: :horizontal_radio_and_checkboxes,    file: :horizontal_file_input,    boolean: :horizontal_boolean } do |f| %>
      <%= f.input :name %>
      <%= f.input :email %>

    <div class="col-sm-11">
      <%= f.submit "送出" , :class => "btn btn-lg btn-danger pull-right" %>
    </div>
  <% end %>
</div>