config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/xadmin', as: 'rails_admin'
  devise_for :users
  root :to => "jobs#index"

  resources :jobs do
    collection do
      get :inform
      post :preview
      get :search
      get :final
    end

    member do
      post :publish
      get :verify
    end
  end

  resources :day_jobs do 
    collection do
      get :inform
      post :preview
      get :search
      get :final
    end

    member do
      post :publish
      get :verify
    end
  end

  resources :categories

  resources :subscriptions do
    member do
      get :verify
    end
  end

  get "/pages/:action" , :controller => "pages"

end

app/views/common/_bootstrap_modal.html.erb
<div id="modal-from-dom" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="modal-from-dom-label" aria-hidden="true">

</div>

app/views/common/_facebook_js.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {return;}
  js = d.createElement(s); js.id = id;

  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=<%= Setting.facebook_app_id%>";

  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/common/_google_analytics.html.erb
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '<%= Setting.google_analytics_key %>']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><%= Setting.app_name %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">



        <li> <%= link_to("日薪專區", day_jobs_path ) %>       </li>

       <li> <%= link_to("關於本站", "/pages/about") %>       </li>
       
       <li>          <%= link_to("訂閱工作快遞", new_subscription_path) %>       </li>
    
       <li> <%= link_to("本站粉絲頁", "https://www.facebook.com/66kjobs", :target => "_blank") %>  </li>

      </ul>

      <ul class="nav navbar-nav navbar-right">

<li>
      <div class="social"> <%=  fb_like(Setting.domain) %>  </div>
</li>
       


          </ul>
        </li>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>